# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-27 01:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import filer.fields.file


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('filer', '0007_auto_20161016_1055'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=300, verbose_name='Nom de catégorie')),
            ],
            options={
                'verbose_name': 'Catégorie',
                'verbose_name_plural': 'Catégories',
            },
        ),
        migrations.CreateModel(
            name='Guide',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guide_name', models.CharField(max_length=300, verbose_name='Nom du guide')),
                ('description', models.TextField(verbose_name='Description du guide')),
                ('author', models.TextField(blank=True, verbose_name='Auteur du guide')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guide.Category')),
                ('document', filer.fields.file.FilerFileField(on_delete=django.db.models.deletion.CASCADE, related_name='guide_documents', to='filer.File')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=200, verbose_name='Tag')),
            ],
            options={
                'ordering': ('tag',),
            },
        ),
        migrations.AddField(
            model_name='guide',
            name='tag',
            field=models.ManyToManyField(blank=True, to='guide.Tag'),
        ),
    ]
