# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-27 01:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import filer.fields.file


class Migration(migrations.Migration):

    dependencies = [
        ('guide', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guide',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guides', to='guide.Category'),
        ),
        migrations.AlterField(
            model_name='guide',
            name='document',
            field=filer.fields.file.FilerFileField(on_delete=django.db.models.deletion.CASCADE, related_name='guides', to='filer.File'),
        ),
        migrations.AlterField(
            model_name='guide',
            name='tag',
            field=models.ManyToManyField(blank=True, related_name='guides', to='guide.Tag'),
        ),
    ]
