# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-09 14:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guide', '0003_category_category_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='color_class',
            field=models.CharField(blank=True, choices=[('label-default', 'label-default'), ('label-primary', 'label-primary'), ('label-success', 'label-success'), ('label-info', 'label-info'), ('label-warning', 'label-warning'), ('label-danger', 'label-danger')], max_length=200, null=True, verbose_name='Bootstrap color class'),
        ),
    ]
