# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-21 01:11
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.deletion
import filer.fields.image


class Migration(migrations.Migration):

    dependencies = [
        ('guide', '0004_tag_color_class'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_img',
            field=filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='img', to='filer.Image'),
        ),
    ]
